host = "0.0.0.0:9090"
env = "dev"
v8_maxcount = 5
v8_lifetime = 0
js_project_path = "jsproj"
static_url_path = "/static"
is_api_delegate = true
internal_api_host = "api.ipapi.com"
internal_api_ip = "api.ipapi.com"
internal_api_port = 80
template_name = "ssr.dev.html"
client_cookie = "gossr_id"
redirect_onerror = ""
ssr_ctx = ["User-Agent","X-Forwarded-For"]
template_vars = [{key = "State", type = "js"},
    {key = "OgImage", type = "html"}]
alarm_url = ""
alarm_secret = ""

[Log]
debug=true
filenum=10
filesize=256
filename="run"
level="DEBUG"
dir="./logs"

